- name: role-elk
  src: https://github.com/jpfork/ansible-elk.git
  version: master
- name: role-grafana
  src: https://github.com/jpfork/Stouts.grafana.git
  version: master
- name: role-deploy-spring-boot-app
  src: https://github.com/jpfork/ansible-role-spring-boot-app.git
  version: master
- name: role-prometheus
  src: https://github.com/jpfork/ansible-prometheus.git
  version: master
- name: role-ntp
  src: https://github.com/jpfork/ansible-role-ntp.git
  version: master
- name: role-nexus
  src: https://github.com/jpfork/ansible-nexus3-oss.git
  version: master
- name: role-java
  src: https://github.com/jpfork/ansible-role-java.git
  version: master
- name: role-sonar
  src: https://github.com/jpfork/ansible-sonar.git
  version: master
- name: role-jenkins
  src: https://github.com/jpfork/ansible-role-jenkins.git
  version: master
- name: role-mysql
  src: https://github.com/jpfork/ansible-role-mysql.git
  version: master
- name: role-git
  src: https://github.com/jpfork/ansible-role-git.git
  version: master
- name: role-ansible
  src: https://github.com/jpfork/ansible-role-ansible.git
  version: master
- name: role-docker
  src: https://github.com/jpfork/ansible-role-docker.git
  version: master
- name: role-pip
  src: https://github.com/jpfork/ansible-role-pip.git
  version: master
- name: role-nodejs
  src: https://github.com/jpfork/ansible-role-nodejs.git
  version: master
- name: role-awx
  src: https://github.com/jpfork/ansible-role-awx.git
  version: master